### ISSUE TITLE
Error in the usage of the SVHunter-Tracer

### ISSUE THREAD

**Issue by mfh10** [xiaofen9/SVHunter#2]
Hello everyone,

I very appreciate your SVHunter tool. However, after building SVHunter-Tracer successfully , i typed this command in order to use the tracer module  : 

java -jar ./target/SVHunter-Tracer-0.1-SNAPSHOT-jar-with-dependencies.jar src/main/java/Main.java config/onosEnv.cfg config/onosSensitiveMethodList.xml config/onosDFMethodList.xml

But I obtain this error message : 

Exception in thread "main" java.lang.NullPointerException
    at Main.addClass(Main.java:33)
    at Main.main(Main.java:145)

Can you help me please to resolve this issue !

Cordialy,

**Comment by shipperzhang** [comment]
I think you misunderstand the argument <path_to_project>. You should add the path to the SDN control project rather than the main function of the Tracer. For example, if you want to parse onos, you should download the ONOS project, compile it and add the path to the compiled result as the first argument.

Thanks for using our tool and I hope this comment helps you.
Jinquan
